export const TAGLINES: string[] = [
  "Hot Off the Repo",
  "Compiled Daily, Served Fresh",
  "Stack Overflow Sold Separately",
  "All Stories Reviewed, None Approved",
  "Now With 30% Fewer Bugs",
  "Read Before You `rm -rf`",
  "Brewed With 100% Open-Source Beans",
  "Two Tabs for One Dollar",
  "Includes Free Trailing Semicolon",
  "Now Compatible With IE11",
  "404: Witty Tagline Not Found",
  "Printed in Monospace, Read in Serif",
  "Cached For Your Convenience",
  "Bring Your Own Coffee",
  "Best Read With CSS Enabled",
  "Estimated Read Time: One Standup",
  "Side Effects May Include Productivity",
  "git pull && read",
  "May Contain Traces of TypeScript",
  "Subscribe, Star, Sigh",
  "Pull Requests Welcomed In Letters",
  "Print Edition Compiled with -O3",
  "No Cookies Were Harmed",
  "Now in Dark Mode (turn the lights off)",
  "Service Workers On Strike Today",
  "Editor-in-Chief: A Markov Chain",
  "Hand-Crafted From Stale Tweets",
  "Powered By Bun, Bound By Time",
  "Includes Optional Chaining",
  "Some Headlines May Throw",
  "Works In Firefox, Mostly",
  "Tabs vs Spaces: Page 12",
  "Free With Your Coffee Hash",
  "All Articles Linted Before Print",
  "Yesterday's News, Cached Today",
  "Subject to Force Push",
  "Memoized for Your Pleasure",
  "We Use Vim, Don't @ Us",
  "Standard Output, Premium Stderr",
  "Editor Wrote This in Notepad",
  "Built With Two Frameworks And Spite",
  "Server-Side Rendered, Reader-Side Confused",
  "Pre-Authenticated, Post-Concerned",
  "All Posts O(n log n) or Faster",
  "Read at Your Own Risk Profile",
  "Powered by Coffee and Tail -F",
  "May Hydrate, May Not",
  "Type Safe Since 2015",
  "Hand-Crafted Artisanal Copy-Paste",
];

export function pickTagline(): string {
  return TAGLINES[Math.floor(Math.random() * TAGLINES.length)];
}
